name: Label bot PR
on:
    pull_request_target:
jobs:
    label_bot_pr:
        runs-on: ubuntu-latest
        if: github.event.pull_request.head.repo.full_name != github.repository && github.actor != 'dependabot[bot]'
        steps:
            - name: Label bot PR
              uses: andymckay/labeler@master
              with:
                  remove-labels: "safe to test"
                  add-labels: "need is safe review"
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

