name: Frontend (PR)
on:
    pull_request_target:
        types: [labeled]
jobs:
    frontend-lint:
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'safe to test')
        steps:
            - name: Remove labels
              uses: andymckay/labeler@master
              with:
                  remove-labels: "need is safe review"
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: yarn
            - run: yarn lint
